# Generated by Django 3.2.6 on 2022-05-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('number_of_party', models.PositiveSmallIntegerField(default=0)),
                ('payment', models.CharField(choices=[('1', 'CARD'), ('2', 'CASH'), ('3', 'PHONE'), ('4', 'BITCOIN')], max_length=20)),
                ('restaurant', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'pos_result_data',
            },
        ),
    ]
